- alias: Restart HA at 3a every day except Shabbat
  trigger:
  - platform: time
    at: 03:30:00
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sun
  action:
  - service: homeassistant.restart
  mode: single

- alias: Turn off the bathroom fan after 10 mins
  trigger:
  - platform: state
    entity_id: switch.hs_downstairs_bathroom_fan
    to: 'on'
    for: 00:10:00
  action:
  - service: switch.turn_off
    entity_id: switch.hs_downstairs_bathroom_fan
  mode: single

- alias: Turn on the exterior lights before sunset
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state_attr('sun.sun', 'elevation') }}"
    below: 7.5
  action:
    service: homeassistant.turn_on
    entity_id: group.exteriorlights

- alias: Turn off the exterior lights after sunrise
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state_attr('sun.sun', 'elevation') }}"
    above: 7.5
  action:
    service: homeassistant.turn_off
    entity_id: group.exteriorlights


