- id: '1605105863267'
  alias: Restart HA
  description: ''
  trigger:
  - platform: time
    at: 03:30:00
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sun
  action:
  - service: homeassistant.restart
  mode: single
- id: '1605107317632'
  alias: Turn on Shabbat Mode
  description: ''
  trigger:
  - platform: state
    entity_id: calendar.home_automation_shabbat
    to: 'on'
    from: 'off'
  action:
  - service: input_boolean.turn_on
    data: {}
    entity_id: input_boolean.shabbat_mode_toggle
  mode: single
- id: '1605215282314'
  alias: Turn the bathroom fan off after 10 mins
  description: ''
  trigger:
  - platform: state
    entity_id: switch.hs_downstairs_bathroom_fan
    to: 'on'
    for: 00:10:00
  action:
  - service: switch.turn_off
    entity_id: switch.hs_downstairs_bathroom_fan
  mode: single
